---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Liverpool FC Age-Utility Graph


```{r}
# pacman::p_load()
library(rvest)
library(polite)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(purrr)
library(stringr)
library(ggrepel)
library(glue)
library(extrafont)
loadfonts(quiet = TRUE)
```

## web-scrape

```{r}
session <- bow("https://www.transfermarkt.com/liverpool-fc/leistungsdaten/verein/31/reldata/GB1%262018/plus/1")

print(session)
# "The path is scrapable for this user-agent": OK, looks like we are good to go!

# grab name from photo element instead
result_name <- scrape(session) %>% 
  html_nodes("#yw1 .bilderrahmen-fixed") %>% 
  html_attr("title") 

# grab age
result_age <- scrape(session) %>% 
  html_nodes(".posrela+ .zentriert") %>% 
  html_text()

# grab minutes played in league
result_mins <- scrape(session) %>% 
  html_nodes("td.rechts") %>% 
  html_text()

```


### combine scraped data

```{r}
# place each vector into list

resultados <- list(result_name, result_age, result_mins)

col_name <- c("name", "age", "minutes")

# then reduce(cbind) to combine them, set names to cols 
results_comb <- resultados %>% 
  reduce(cbind) %>% 
  as_tibble() %>% 
  set_names(col_name)

# NOICE.gif
glimpse(results_comb)
```

## clean data

### fix ages via Wikipedia squad page

```{r}
wiki_url <- "https://en.wikipedia.org/wiki/2019–20_Liverpool_F.C._season"

wiki_session <- bow(wiki_url)

wiki_age <- scrape(wiki_session) %>% 
  html_nodes("table.wikitable:nth-child(6)") %>% 
  html_table(fill = TRUE) %>% 
  flatten_df()



```


### more cleaning

```{r}
age_plus_one <- c("Lovren", "Van Dijk", "Moreno", "Ings")

# fix "strings" into proper formats, calculate % of minutes appeared
lfc_minutes <- results_comb %>% 
  
  mutate(age = as.numeric(age),
         minutes = minutes %>% 
           str_replace("\\.", "") %>% 
           str_replace("'", "") %>% 
           as.numeric(),
         min_perc = (minutes / 3420) %>% round(digits = 3)) %>% 
  
  filter(!is.na(minutes)) %>% 
  
  separate(name, into = c("first_name", "last_name"), sep = " ") %>% 
  
  # manually fix some names
  mutate(
    last_name = case_when(                        
      first_name == "Trent" ~ "Alexander-Arnold",   
      first_name == "Virgil" ~ "Van Dijk",
      first_name == "Alex" ~ "Oxlade-Chamberlain",
      TRUE ~ last_name),
    age = age + 1) %>%    # do CURRENT age instead for plot 2.0
  
  mutate(
    age = case_when(
      last_name %in% age_plus_one ~ age + 1,
      TRUE ~ age)
    ) %>% 
  arrange(desc(min_perc))

# rectanglular highlight for players in their prime:
rect_df <- data.frame(
  xmin = 25, xmax = 30,
  ymin = -Inf, ymax = Inf
)
```




## plotting

```{r fig.height=6, fig.width=8}
lfc_minutes %>% 
  ggplot(aes(x = age, y = min_perc)) +
  geom_rect(
    data = rect_df, inherit.aes = FALSE,
    aes(xmin = xmin, xmax = xmax, 
        ymin = ymin, ymax = ymax),
    alpha = 0.3,
    fill = "firebrick1") +
  geom_point(color = "red", size = 2.5) +
  geom_text_repel(
    aes(label = last_name, family = "Roboto Condensed"),
    nudge_x = 0.5,
    seed = 6) + 
  scale_y_continuous(
    expand = c(0.01, 0),
    limits = c(0, 1), 
    labels = percent_format()) +
  scale_x_continuous(
    breaks = pretty_breaks(n = 10)) +
  labs(
    x = "Current Age (As of Aug. --th, 2019)", y = "% of Minutes Played", 
    title = "Liverpool FC: Age-Utility Matrix",
    subtitle = "Premier League 18/19 (Summer 2019 transfers in bold, departed players left in for comparison)",
    caption = glue::glue("
                         Data: transfermarkt.com
                         By: @R_by_Ryo")) +
  theme_bw() +
  theme(
    text = element_text(family = "Roboto Condensed"),
    panel.grid.minor.y = element_blank()) +
  geom_label(
    aes(x = 20.5, y = 0.87, 
        hjust = 0.5, 
        label = glue("
          Encouraging to see Liverpool buying players both in 
          their prime and regulars in their previous teams. 
          Our entire best 'Starting XI' are going to be 
          in their prime this season!
          "), 
        family = "Roboto Condensed"),
    size = 3.5)

```









# NEW 


## web-scrape




### combine


## clean



## plot


## legend plot


## combine plot






# NEW age-utility

```{r, message=FALSE, warning=FALSE}
pacman::p_load(tidyverse, polite, scales, ggimage, rvest, 
               glue, extrafont, showtext, ggrepel, magick, 
               ggforce, lubridate, cowplot, patchwork, rlang)
loadfonts()
```

## team links function

```{r}
get_team_links <- function(season) {
  
  url <- "https://www.transfermarkt.com/premier-league/startseite/wettbewerb/GB1/plus/?saison_id={season}"
  
  session <- bow(url)
  
  team_links <- scrape(session) %>% 
    html_nodes("#yw1 > table > tbody > tr > td.zentriert.no-border-rechts > a") %>% 
    html_attr("href")
  
 # season <- enquo(season)
  
  team_links_df <- team_links %>% 
    enframe(name = NULL) %>% 
    separate(value, c(NA, "team_name", NA, NA, "team_num", NA, NA), sep = "/") %>% 
    mutate(link = glue("https://www.transfermarkt.com/{team_name}/leistungsdaten/verein/{team_num}/reldata/%26{season}/plus/1"),
           season = season)
}
```

```{r}
team_links_df <- get_team_links(season = 2019)

glimpse(team_links_df)
```



## scrape function

```{r}
epl_age_utility_info <- function(team_name, team_num, season) {
  ## get age + minutes played
  session <- bow(glue::glue("https://www.transfermarkt.com/{team_name}/leistungsdaten/verein/{team_num}/reldata/%26{season}/plus/1"))
  
  # grab name from photo element instead
  result_name <- scrape(session) %>% 
    html_nodes("#yw1 .bilderrahmen-fixed") %>% 
    html_attr("title") 
  
  # grab age
  result_age <- scrape(session) %>% 
    html_nodes(".posrela+ .zentriert") %>% 
    html_text()
  
  # grab minutes played in league
  result_mins <- scrape(session) %>% 
    html_nodes("td.rechts") %>% 
    html_text()
  
  ## get length
  session <- bow(glue::glue("https://www.transfermarkt.com/{team_name}/kader/verein/{team_num}/saison_id/{season}/plus/1"))
  
  result_name2 <- scrape(session) %>% 
    html_nodes("#yw1 .bilderrahmen-fixed") %>% 
    html_attr("title") 
  
  result_bday <- scrape(session) %>% 
    html_nodes(".posrela+ .zentriert") %>% 
    html_text()
  
  result_joinedteam <- scrape(session) %>% 
    html_nodes("td:nth-child(7)") %>% 
    html_text()
  
  result_leaveteam <- scrape(session) %>% 
    html_nodes("td:nth-child(9)") %>% 
    html_text()
  
  # place each vector into list
  resultados <- list(result_name, result_age, result_mins)
  
  col_name <- c("name", "age", "minutes")
  
  results_comb <- resultados %>% 
    reduce(cbind) %>% 
    as_tibble() %>% 
    set_names(col_name)
  
  ## join + bday
  resultados2 <- list(result_name2, result_bday, 
                      result_joinedteam, result_leaveteam)
  
  col_name2 <- c("name", "bday", "join", "leave")
  
  results_comb2 <- resultados2 %>% 
    reduce(cbind) %>% 
    as_tibble() %>% 
    set_names(col_name2)
  
  ## combine BOTH
  results_comb <- results_comb %>% 
    left_join(results_comb2) 
  
  # fix "strings" into proper formats, calculate % of minutes appeared
  all_team_minutes <- results_comb %>% 
    mutate(age = as.numeric(age),
           minutes = minutes %>% 
             str_replace("\\.", "") %>% 
             str_replace("'", "") %>% 
             as.numeric(),
           min_perc = (minutes / 3060) %>% round(digits = 3),
           bday = str_replace_all(bday, "\\(.*\\)", "") %>% mdy(),
           join = join %>% mdy(),
           join_age = interval(bday, join) / years(1),
           age_now = interval(bday, Sys.Date()) / years(1)) %>% 
    filter(!is.na(minutes)) %>% 
    separate(name, into = c("first_name", "last_name"), 
             sep = " ", fill = "left") %>%
    mutate(
      fname = if_else(!is.na(first_name), 
                      str_extract(first_name, "[A-Z]{1}"),
                      ""),
      player = case_when(
        !is.na(first_name) ~ glue("{fname}. {last_name}"),
        TRUE ~ last_name),
      team_name = team_name,
      team_name = case_when(
        team_name == "shimizu-s-pulse" ~ "Shimizu S-Pulse",
        team_name == "fc-tokyo" ~ "FC Tokyo", 
        team_name == "fc-liverpool" ~ "Liverpool FC",
        team_name == "yokohama-f-marinos" ~ "Yokohama F. Marinos",
        TRUE ~ str_replace_all(team_name, "-", " ") %>% stringr::str_to_title()),
      season = season) %>% 
    arrange(desc(min_perc)) 
  
  return(all_team_minutes)
}
```

```{r}
# ALL 18 TEAMS AT ONCE, WILL TAKE A WHILE:
age_utility_df_ALL <- pmap(list(team_links_df$team_name, 
                                team_links_df$team_num,
                                team_links_df$season),
                             .f = epl_age_utility_info)

epl_age_utility_df <- age_utility_df_ALL %>% 
  reduce(rbind)

## save
saveRDS(epl_age_utility_df, file = glue("{here::here()}/data/epl_age_utility_df_1920.RDS"))
```

## all team data

```{r}
epl_age_utility_df <- readRDS(file = here::here("data/epl_age_utility_df_1920.RDS"))
```


# Plot

```{r fig.width=15, fig.height=8}
combined_plot <- age_utility_plotter(df = all_team_minutes, 
                    team_name = "Liverpool FC",
                    j_name = "Liverpool FC",
                    color_1 = "red", color_2 = "firebrick1",
                    img_path = here::here("img/LiverpoolFC.png"))

combined_plot
```


```{r}
ggsave(plot = combined_plot, "../Premier League 2019-2020/output/LFC_age_utility_22620.png",
       height = 8, width = 15)
```




