---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r, message=FALSE, warning=FALSE}
pacman::p_load(tidyverse, polite, scales, ggimage, rvest, 
               glue, extrafont, showtext, ggrepel, magick, 
               ggforce, lubridate, cowplot, patchwork)
loadfonts()
```

# functions

## add_logo functions

```{r}
add_logo <- function(plot_path, logo_path, logo_position, logo_scale = 10){

    # Requires magick R Package https://github.com/ropensci/magick

    # Useful error message for logo position
    if (!logo_position %in% c("top right", "top left", "bottom right", "bottom left")) {
        stop("Error Message: Uh oh! Logo Position not recognized\n  Try: logo_positon = 'top left', 'top right', 'bottom left', or 'bottom right'")
    }

    # read in raw images
    plot <- magick::image_read(plot_path)
    logo_raw <- magick::image_read(logo_path)

    # get dimensions of plot for scaling
    plot_height <- magick::image_info(plot)$height
    plot_width <- magick::image_info(plot)$width

    # default scale to 1/10th width of plot
    # Can change with logo_scale
    logo <- magick::image_scale(logo_raw, as.character(plot_width/logo_scale))

    # Get width of logo
    logo_width <- magick::image_info(logo)$width
    logo_height <- magick::image_info(logo)$height

    # Set position of logo
    # Position starts at 0,0 at top left
    # Using 0.01 for 1% - aesthetic padding

    if (logo_position == "top right") {
        x_pos = plot_width - logo_width - 0.01 * plot_width
        y_pos = 0.01 * plot_height
    } else if (logo_position == "top left") {
        x_pos = 0.01 * plot_width
        y_pos = 0.01 * plot_height
    } else if (logo_position == "bottom right") {
        x_pos = plot_width - logo_width - 0.01 * plot_width
        y_pos = plot_height - logo_height - 0.01 * plot_height
    } else if (logo_position == "bottom left") {
        x_pos = 0.01 * plot_width
        y_pos = plot_height - logo_height - 0.01 * plot_height
    }

    # Compose the actual overlay
    magick::image_composite(plot, logo, offset = paste0("+", x_pos, "+", y_pos))

}
```

## tategaki function

```{r}
tategaki <- function(x){
  x <- chartr("ー", "丨", x) # 長音符の処理
  x <- strsplit(split="", x)
  sapply(x, paste, collapse="\n")
}

tategaki_alt <- function(x){
  x <- stringr::str_replace_all(x, "ー", "丨") # 長音符の処理
  stringr::str_wrap(x, width = 1)
}
```




# FC Tokyo

## scrape Tokyo

```{r}
session <- bow("https://www.transfermarkt.com/fc-tokyo/leistungsdaten/verein/6631/plus/0?reldata=JAP1%262018")

print(session)

# grab name from photo element instead
result_name <- scrape(session) %>% 
  html_nodes("#yw1 .bilderrahmen-fixed") %>% 
  html_attr("title") 

# grab age
result_age <- scrape(session) %>% 
  html_nodes(".posrela+ .zentriert") %>% 
  html_text()

# grab minutes played in league
result_mins <- scrape(session) %>% 
  html_nodes("td.rechts") %>% 
  html_text()
```


## scrape length

```{r}
session <- bow("https://www.transfermarkt.com/fc-tokyo/kader/verein/6631/plus/1/galerie/0?saison_id=2018")

result_name2 <- scrape(session) %>% 
  html_nodes("#yw1 .bilderrahmen-fixed") %>% 
  html_attr("title") 

result_bday <- scrape(session) %>% 
  html_nodes(".posrela+ .zentriert") %>% 
  html_text()

result_joinedteam <- scrape(session) %>% 
  html_nodes("td:nth-child(8)") %>% 
  html_text()

result_leaveteam <- scrape(session) %>% 
  html_nodes("td:nth-child(10)") %>% 
  html_text()
```





## clean tokyo

```{r}
# place each vector into list
resultados <- list(result_name, result_age, result_mins)

col_name <- c("name", "age", "minutes")

results_comb <- resultados %>% 
  reduce(cbind) %>% 
  as_tibble() %>% 
  set_names(col_name)

## join + bday
resultados2 <- list(result_name2, result_bday, 
                    result_joinedteam, result_leaveteam)

col_name2 <- c("name", "bday", "join", "leave")

results_comb2 <- resultados2 %>% 
  reduce(cbind) %>% 
  as_tibble() %>% 
  set_names(col_name2)

## combine BOTH
results_comb <- results_comb %>% 
  left_join(results_comb2) 

# fix "strings" into proper formats, calculate % of minutes appeared
tokyo_minutes <- results_comb %>% 
  mutate(age = as.numeric(age),
         minutes = minutes %>% 
           str_replace("\\.", "") %>% 
           str_replace("'", "") %>% 
           as.numeric(),
         min_perc = (minutes / 3060) %>% round(digits = 3),
         bday = str_replace_all(bday, "\\(.*\\)", "") %>% mdy(),
         join = join %>% mdy(),
         join_age = case_when(
           name == "Hirotaka Mita" ~ 29,
           TRUE ~ interval(bday, join) / years(1)),
         age_now = case_when(
           name == "Takefusa Kubo" ~ 17,
           TRUE ~ interval(bday, Sys.Date()) / years(1))) %>% 
  filter(!is.na(minutes)) %>% 
  separate(name, into = c("first_name", "last_name"), 
           sep = " ", fill = "left") %>%
  mutate(join_age = case_when(
           last_name == "Oh" ~ 29,
           TRUE ~ join_age),
         fname = if_else(!is.na(first_name), 
                         str_extract(first_name, "[A-Z]{1}"),
                         ""),
         player = case_when(
    !is.na(first_name) ~ glue("{fname}. {last_name}"),
    TRUE ~ last_name)) %>% 
  arrange(desc(min_perc))

glimpse(tokyo_minutes)
```

## plot Tokyo

"ピーク年齢"

```{r fig.height=8, fig.width=12}
# font_add_google("Noto Sans", "Noto Sans")
# showtext_auto()

# rectanglular highlight for players in their prime:
rect_df <- data.frame(
  xmin = 25, xmax = 29,
  ymin = 0, ymax = 1
)

fctokyo_plot <- tokyo_minutes %>% 
  ggplot(aes(x = age_now, y = min_perc)) +
  geom_vline(xintercept = 25, alpha = 0.4, color = "grey20") +
  geom_hline(yintercept = 0.5, alpha = 0.4, color = "grey20") +
  geom_rect(data = rect_df,
            aes(x = NULL, y = NULL,
                xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#271672", alpha = 0.4) +
  geom_link(aes(x = join_age, xend = age_now,
                y = min_perc, yend = min_perc,
                alpha = stat(index)), 
            color = "#DD2220", size = 1.75) + 
  geom_point(aes(x = age_now), color = "#DD2220", size = 3.5) +
  geom_text_repel(
    aes(label = player),
    nudge_y = 0.01, 
    seed = 6) + 
  annotate("text", x = 27, y = 1.055,
           size = 5.5, fontface = "bold",
           family = "Yu Mincho Demibold",
           label = "ピーク年齢", color = "grey20") +
  scale_y_continuous(
    expand = c(0.01, 0),
    limits = c(0, 1.08), 
    breaks = seq(0, 1, by = 0.2), 
    labels = percent_format()) +
  scale_x_continuous(
    limits = c(16, 33),
    breaks = seq(18, 34, by = 2)) +
  labs(
    x = "年齢", 
    y = tategaki_alt("出場時間 (%)"),  
    title = "FC東京: 年齢-出場時間",
    subtitle = "J-League 2019 Season (100% = 3060分)") +
  theme_bw() +
  theme(
    text = element_text(family = "Yu Mincho Demibold"),
    panel.border = element_blank(),
    plot.title = element_text(color = "#271672", size = 20, face = "bold"),
    plot.subtitle = element_text(color = "#DD2220", size = 18),
    plot.caption = element_text(size = 14),
    panel.grid.minor = element_blank(),
    axis.title.y = element_text(angle = 0, vjust= 0.5),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
    axis.ticks = element_blank(),
    legend.position = "none")

fctokyo_plot
```

```{r}
ggsave(plot = fctokyo_plot, "../J-League 2020/output/fctokyo_plot.png",
       height = 8, width = 12)
```



```{r}
plot_logo <- add_logo(plot_path = "../J-League 2020/output/fctokyo_plot.png",
                      logo_path = "https://upload.wikimedia.org/wikipedia/en/4/45/FCTokyo.png",
                      logo_position = "top right",
                      logo_scale = 23)

plot_logo
```

```{r}
image_write(image = plot_logo, "../J-League 2020/output/fctokyo_logo_plot.png")
```


## legend plot

```{r fig.width=3, fig.height=5}
leg_df <- tibble(x = 23, xend = 28,
                 y = 0.65, yend = 0.65)


legend_plot <- tokyo_minutes %>% 
  ggplot(aes(x = age_now, y = min_perc)) +
  geom_rect(data = rect_df,
            aes(x = NULL, y = NULL,
                xmin = xmin, xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#271672", alpha = 0.4) +
  geom_link(data = leg_df,
            aes(x = x, xend = xend,
                y = y, yend = yend,
                alpha = stat(index)), 
            color = "#DD2220", size = 1.75) + 
  geom_point(x = 28, y = 0.65, color = "#DD2220", size = 3.5) +
  ## top arrow
  geom_curve(x = 30, xend = 28.4,
             y = 0.77, yend = 0.65,
             curvature = -0.5, size = 1.2,
             arrow = arrow(length = unit(0.1, "inches")),
             lineend = "round") +
  ## bottom arrow
  geom_segment(x = 23, xend = 23,
               y = 0.48, yend = 0.63,
               size = 1.2,
               arrow = arrow(length = unit(0.1, "inches")),
               lineend = "round") +
  annotate("text", x = 30, y = 0.83, family = "Yu Mincho Demibold",
           label = "年齢", size = 4.5) +
  annotate("text", x = 23, y = 0.4, family = "Yu Mincho Demibold",
           label = "年齢 （入団時）", size = 4.5) +
  scale_y_continuous(
    limits = c(0, 1.05), 
    breaks = seq(0, 1, by = 0.2),
    labels = percent_format()) +
  scale_x_continuous(
    limits = c(18, 33),
    breaks = seq(18, 34, by = 2)) +
  labs(caption = glue("
                   データ: transfermarkt.com
                   作: @R_by_Ryo")) +
  theme_bw() +
  theme(
    text = element_text(family = "Yu Mincho Demibold"),
    panel.border = element_blank(),
    plot.caption = element_text(size = 14),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.text = element_text(size = 10),
    legend.position = "none")

legend_plot
```



## age histogram


```{r fig.width=3, fig.height=5}
tokyo_minutes %>% 
  mutate(team = "FC Tokyo") %>% 
  select(team, age) %>% 
  #spread("team", "age") %>% 
  ggplot(aes(x = age, y = team), groupOnX = TRUE) +
  ggbeeswarm::geom_beeswarm()


tokyo_minutes %>% 
  ggplot(aes(age)) +
  geom_freqpoly(binwidth = 1.5)


tokyo_minutes %>% 
  mutate(team = "FC Tokyo") %>% 
  ggplot(aes(age, team)) +
  ggridges::geom_density_ridges(scale = 4) +
  scale_y_discrete(expand = c(0.05, 0))


tokyo_minutes %>% 
  add_count(age) %>% 
  ggplot(aes(as.factor(age), n)) +
  ggridges::geom_density_ridges()
  mutate(team = "FC Tokyo") %>% 
  group_by(age) %>% 
  summarize(tot = n()) %>% 
  ungroup() %>% 
  ggplot(aes(age, tot, height = tot)) +
  ggridges::geom_ridgeline()
  
  
tokyo_minutes %>% 
  add_count(age) %>% 
  ggplot(aes(as.factor(age), n)) +
  geom_col()

tokyo_minutes %>% 
  ggplot(aes(age)) +
  geom_density(#aes(y = ..count..), 
               fill = "grey20") +
  geom_vline(aes(xintercept = median(age)), color = "red") +
  scale_x_continuous(limits = c(8, 40)) +
  scale_y_continuous(limits = c(0, 0.1))
```


## summary stats

```{r fig.width=3, fig.height=5}
tokyo_minutes %>% 
  mutate(duration = age_now - join_age) %>% 
  summarize(median_age = median(age),
            median_duration = median(duration),
            sum_players = n())
```

```{r fig.width=3, fig.height=5}
summary_stats <- tokyo_minutes %>%
  ggplot(aes(x = age_now, y = min_perc)) +
  annotate("text", x = 25, y = 0.75, 
           size = 4,
           label = "Number of Players: 25",
           family = "Yu Mincho Demibold") +
  annotate("text", x = 25, y = 0.65, 
           size = 4,
           label = "Median Age: 24",
           family = "Yu Mincho Demibold") +
  annotate("text", x = 25, y = 0.55, 
           size = 4,
           label = "Median Length of Stay: 2.59 Years",
           family = "Yu Mincho Demibold") +
  theme_void()

summary_stats
```


## combine


```{r fig.height=8, fig.width=12}
fctokyo_plot +
  theme(plot.margin = unit(c(1, 10, 1, 1), "cm"))

legend_plot
```




```{r fig.width=15, fig.height=8}
ggdraw(plot_grid(fctokyo_plot, legend_plot, 
                 rel_heights = c(2, 1)))


ggdraw() +
  draw_plot(fctokyo_plot) +
  draw_plot(legend_plot, hjust = 10, 
            width = 0.13, height = 0.2)


ggdraw(fctokyo_plot +
  theme(plot.margin = unit(c(1, 10, 1, 1), "cm"))) +
  draw_plot(legend_plot, 1, 0,
            width = 0.13, height = 0.2)
```



```{r fig.width=15, fig.height=8}
layout <- "
AAAA##
AAAAC#
AAAA##
AAAAB#
"

combined_plot <- fctokyo_plot + legend_plot + summary_stats + 
  plot_layout(design = layout)

combined_plot
```



```{r}
ggsave(plot = combined_plot, "../J-League 2020/output/fctokyo_combplot.png",
       height = 8, width = 15)
```



```{r}
plot_logo <- add_logo(plot_path = "../J-League 2020/output/fctokyo_combplot.png",
                      logo_path = "https://upload.wikimedia.org/wikipedia/en/4/45/FCTokyo.png",
                      logo_position = "top right",
                      logo_scale = 23)

plot_logo
```

```{r}
image_write(image = plot_logo, "../J-League 2020/output/fctokyo_logo_combplot.png")
```






# all teams



```{r}
get_team_links <- function(season) {
  
  url <- "https://www.transfermarkt.com/j1-league/startseite/wettbewerb/JAP1/plus/?saison_id={season}"
  
  session <- bow(url)
  
  team_links <- scrape(session) %>% 
    html_nodes("#yw1 > table > tbody > tr > td.zentriert.no-border-rechts > a") %>% 
    html_attr("href")
  
 # season <- enquo(season)
  
  team_links_df <- team_links %>% 
    enframe(name = NULL) %>% 
    separate(value, c(NA, "team_name", NA, NA, "team_num", NA, NA), sep = "/") %>% 
    mutate(link = glue("https://www.transfermarkt.com/{team_name}/leistungsdaten/verein/{team_num}/reldata/JAP1%26{season}/plus/1"),
           season = season)
}
```

```{r}
team_links_df <- get_team_links(season = 2018)

glimpse(team_links_df)
```


```{r}
jleague_age_utility_info <- function(team_name, team_num, season) {
  ## get age + minutes played
  session <- bow(glue::glue("https://www.transfermarkt.com/{team_name}/leistungsdaten/verein/{team_num}/plus/0?reldata=JAP1%26{season}"))
  
  # grab name from photo element instead
  result_name <- scrape(session) %>% 
    html_nodes("#yw1 .bilderrahmen-fixed") %>% 
    html_attr("title") 
  
  # grab age
  result_age <- scrape(session) %>% 
    html_nodes(".posrela+ .zentriert") %>% 
    html_text()
  
  # grab minutes played in league
  result_mins <- scrape(session) %>% 
    html_nodes("td.rechts") %>% 
    html_text()
  
  ## get length
  session <- bow(glue::glue("https://www.transfermarkt.com/{team_name}/kader/verein/{team_num}/plus/1/galerie/0?saison_id={season}"))
  
  result_name2 <- scrape(session) %>% 
    html_nodes("#yw1 .bilderrahmen-fixed") %>% 
    html_attr("title") 
  
  result_bday <- scrape(session) %>% 
    html_nodes(".posrela+ .zentriert") %>% 
    html_text()
  
  result_joinedteam <- scrape(session) %>% 
    html_nodes("td:nth-child(8)") %>% 
    html_text()
  
  result_leaveteam <- scrape(session) %>% 
    html_nodes("td:nth-child(10)") %>% 
    html_text()
  
  # place each vector into list
  resultados <- list(result_name, result_age, result_mins)
  
  col_name <- c("name", "age", "minutes")
  
  results_comb <- resultados %>% 
    reduce(cbind) %>% 
    as_tibble() %>% 
    set_names(col_name)
  
  ## join + bday
  resultados2 <- list(result_name2, result_bday, 
                      result_joinedteam, result_leaveteam)
  
  col_name2 <- c("name", "bday", "join", "leave")
  
  results_comb2 <- resultados2 %>% 
    reduce(cbind) %>% 
    as_tibble() %>% 
    set_names(col_name2)
  
  ## combine BOTH
  results_comb <- results_comb %>% 
    left_join(results_comb2) 
  
  # fix "strings" into proper formats, calculate % of minutes appeared
  all_team_minutes <- results_comb %>% 
    mutate(age = as.numeric(age),
           minutes = minutes %>% 
             str_replace("\\.", "") %>% 
             str_replace("'", "") %>% 
             as.numeric(),
           min_perc = (minutes / 3060) %>% round(digits = 3),
           bday = str_replace_all(bday, "\\(.*\\)", "") %>% mdy(),
           join = join %>% mdy(),
           join_age = interval(bday, Sys.Date()) / years(1)) %>% 
    filter(!is.na(minutes)) %>% 
    separate(name, into = c("first_name", "last_name"), 
             sep = " ", fill = "left") %>%
    mutate(
      fname = if_else(!is.na(first_name), 
                      str_extract(first_name, "[A-Z]{1}"),
                      ""),
      player = case_when(
        !is.na(first_name) ~ glue("{fname}. {last_name}"),
        TRUE ~ last_name),
      team_name = team_name,
      season = season) %>% 
    arrange(desc(min_perc))
  
  return(all_team_minutes)
}
```

```{r}
# ALL 18 TEAMS AT ONCE, WILL TAKE A WHILE:
age_utility_df_ALL <- pmap(list(team_links_df$team_name, 
                                team_links_df$team_num,
                                team_links_df$season),
                             .f = jleague_age_utility_info)

jleague_age_utility_df <- age_utility_df_ALL %>% 
  reduce(rbind)

## save
saveRDS(jleague_age_utility_df, file = glue("{here::here()}/data/jleague_age_utility_df_2019.RDS"))
```







