---
title: "Untitled"
author: "RN7"
date: "1/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# pkgs

```{r, message=FALSE, warning=FALSE}
pacman::p_load(tidyverse, polite, scales, ggimage, 
               ggforce, ggtext,
               rvest, glue, extrafont, ggrepel, magick)
loadfonts()
```

## add_logo

```{r}
add_logo <- function(plot_path, logo_path, logo_position, 
                     logo_scale = 10){

    # Requires magick R Package https://github.com/ropensci/magick

    # Useful error message for logo position
    if (!logo_position %in% c("top right", "top left", "bottom right", "bottom left")) {
        stop("Error Message: Uh oh! Logo Position not recognized\n  Try: logo_positon = 'top left', 'top right', 'bottom left', or 'bottom right'")
    }

    # read in raw images
    plot <- magick::image_read(plot_path)
    logo_raw <- magick::image_read(logo_path)

    # get dimensions of plot for scaling
    plot_height <- magick::image_info(plot)$height
    plot_width <- magick::image_info(plot)$width

    # default scale to 1/10th width of plot
    # Can change with logo_scale
    logo <- magick::image_scale(logo_raw, as.character(plot_width/logo_scale))

    # Get width of logo
    logo_width <- magick::image_info(logo)$width
    logo_height <- magick::image_info(logo)$height

    # Set position of logo
    # Position starts at 0,0 at top left
    # Using 0.01 for 1% - aesthetic padding

    if (logo_position == "top right") {
        x_pos = plot_width - logo_width - 0.01 * plot_width
        y_pos = 0.01 * plot_height
    } else if (logo_position == "top left") {
        x_pos = 0.01 * plot_width
        y_pos = 0.01 * plot_height
    } else if (logo_position == "bottom right") {
        x_pos = plot_width - logo_width - 0.01 * plot_width
        y_pos = plot_height - logo_height - 0.01 * plot_height
    } else if (logo_position == "bottom left") {
        x_pos = 0.01 * plot_width
        y_pos = plot_height - logo_height - 0.01 * plot_height
    }

    # Compose the actual overlay
    magick::image_composite(plot, logo, offset = paste0("+", x_pos, "+", y_pos))
}
```

# Bundesliga data

## fbref

- Save "Player Standard Stats" & "Squad Standard Stats" as a `.csv` file or whatever you prefer.
- https://fbref.com/en/comps/20/passing/Bundesliga-Stats

### player stats

```{r}
buli_player_passing_stats_hinrunde_raw <- read_csv(here::here("data/buli_player_passing_stats_hinrunde.csv"),
                                  skip = 1, col_names = TRUE)

buli_player_passing_stats_hinrunde <- buli_player_passing_stats_hinrunde_raw %>% 
  rename_at(vars(14:16), 
            ~ glue::glue("short_{colnames(buli_player_passing_stats_hinrunde_raw)[14:16]}")) %>% 
  rename_at(vars(17:19), 
            ~ glue::glue("medium_{colnames(buli_player_passing_stats_hinrunde_raw)[17:19]}")) %>% 
  rename_at(vars(20:22), 
            ~ glue::glue("long_{colnames(buli_player_passing_stats_hinrunde_raw)[20:22]}")) %>% 
  rename_all(~str_replace_all(colnames(buli_player_passing_stats_hinrunde), "_[0-9]", "")) %>% 
  select(-Matches, -Rk)

glimpse(buli_player_passing_stats_hinrunde)
```

```{r}
## save
saveRDS(buli_player_passing_stats_hinrunde, 
        file = glue("{here::here()}/data/buli_player_passing_stats_hinrunde.RDS"))

buli_player_passing_stats_hinrunde <- readRDS(
  file = glue("{here::here()}/data/buli_player_passing_stats_hinrunde.RDS"))
```

```{r}
buli_player_passing_hinrunde_clean <- buli_player_passing_stats_hinrunde %>% 
  separate(Player, into = c("fullname", "allname"), sep = "\\\\") %>%   separate(fullname, into = c("firstname", "lastname"),
           sep = "\\s", extra = "merge",
           remove = FALSE) %>%
  mutate(fname = str_extract(firstname, "[A-Z]{1}")) %>% 
  ## players like Fabinho listed without Tavares last name
  mutate(player = if_else(is.na(lastname), firstname, lastname)) %>% 
  mutate(player = case_when(
    !is.na(lastname) ~ glue("{fname}. {lastname}"),
    TRUE ~ firstname)) %>% 
  mutate(min = `90s` * 90) %>% 
  mutate(KPper90 = (KP / min) * 90,
         xAper90 = (xA / min) * 90,
         finalthirdper90 = (`1/3` / min) * 90,
         PPAper90 = (PPA / min) * 90,
         CrsPAper90 = (CrsPA / min) * 90,
         TBper90 = (TB / min) * 90) %>% 
  ## keep fullname so can differentiate A. Gomes (Andre/Angel), etc.
  select(-`90s`, -firstname, -lastname, -allname, 
         team_name = Squad, -fname) 

glimpse(buli_player_passing_hinrunde_clean)
```


```{r}
## save
saveRDS(buli_player_passing_hinrunde_clean, 
        file = glue("{here::here()}/data/buli_player_passing_hinrunde_clean.RDS"))

buli_player_passing_hinrunde_clean <- readRDS(
  file = glue("{here::here()}/data/buli_player_passing_hinrunde_clean.RDS"))
```










